# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\user\durgesh.n\workspace\SHIVA-V2\ui\production.ui'
#
# Created: Mon Jun 12 17:52:13 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(926, 538)
        self.frame = QtGui.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(9, 9, 916, 520))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 901, 501))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.project_cb = QtGui.QComboBox(self.tab)
        self.project_cb.setObjectName("project_cb")
        self.verticalLayout.addWidget(self.project_cb)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.episode_cb = QtGui.QComboBox(self.tab)
        self.episode_cb.setObjectName("episode_cb")
        self.verticalLayout_2.addWidget(self.episode_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.dept_cb = QtGui.QComboBox(self.tab)
        self.dept_cb.setObjectName("dept_cb")
        self.verticalLayout_3.addWidget(self.dept_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.emplyee_le = QtGui.QLineEdit(self.tab)
        self.emplyee_le.setObjectName("emplyee_le")
        self.verticalLayout_4.addWidget(self.emplyee_le)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.assign_pb = QtGui.QPushButton(self.tab)
        self.assign_pb.setObjectName("assign_pb")
        self.horizontalLayout_2.addWidget(self.assign_pb)
        self.approve_pb = QtGui.QPushButton(self.tab)
        self.approve_pb.setObjectName("approve_pb")
        self.horizontalLayout_2.addWidget(self.approve_pb)
        self.retake_pb = QtGui.QPushButton(self.tab)
        self.retake_pb.setObjectName("retake_pb")
        self.horizontalLayout_2.addWidget(self.retake_pb)
        self.reassign_pb = QtGui.QPushButton(self.tab)
        self.reassign_pb.setObjectName("reassign_pb")
        self.horizontalLayout_2.addWidget(self.reassign_pb)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 30, 221, 17))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(40, 110, 231, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(490, 30, 251, 17))
        self.label_7.setObjectName("label_7")
        self.activeEmployee_lw = QtGui.QListWidget(self.tab_2)
        self.activeEmployee_lw.setGeometry(QtCore.QRect(40, 131, 231, 271))
        self.activeEmployee_lw.setObjectName("activeEmployee_lw")
        self.dept_lw = QtGui.QListWidget(self.tab_2)
        self.dept_lw.setGeometry(QtCore.QRect(490, 51, 256, 351))
        self.dept_lw.setObjectName("dept_lw")
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        self.addEmployee_pb = QtGui.QPushButton(self.tab_2)
        self.addEmployee_pb.setGeometry(QtCore.QRect(760, 210, 99, 27))
        self.addEmployee_pb.setObjectName("addEmployee_pb")
        self.layoutWidget = QtGui.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 60, 311, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addEmployee_le = QtGui.QLineEdit(self.layoutWidget)
        self.addEmployee_le.setObjectName("addEmployee_le")
        self.horizontalLayout_4.addWidget(self.addEmployee_le)
        self.checkAvailability_pb = QtGui.QPushButton(self.layoutWidget)
        self.checkAvailability_pb.setObjectName("checkAvailability_pb")
        self.horizontalLayout_4.addWidget(self.checkAvailability_pb)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Select Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Select Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Select Department", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Select Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.emplyee_le.setPlaceholderText(QtGui.QApplication.translate("Form", "Enter name here..", None, QtGui.QApplication.UnicodeUTF8))
        self.assign_pb.setText(QtGui.QApplication.translate("Form", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_pb.setText(QtGui.QApplication.translate("Form", "Approoved", None, QtGui.QApplication.UnicodeUTF8))
        self.retake_pb.setText(QtGui.QApplication.translate("Form", "Retake", None, QtGui.QApplication.UnicodeUTF8))
        self.reassign_pb.setText(QtGui.QApplication.translate("Form", "Reassign", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Assign Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Add New Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Active Employees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Departments", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.dept_lw.isSortingEnabled()
        self.dept_lw.setSortingEnabled(False)
        self.dept_lw.item(0).setText(QtGui.QApplication.translate("Form", "ani", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(1).setText(QtGui.QApplication.translate("Form", "art", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(2).setText(QtGui.QApplication.translate("Form", "cbs", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(3).setText(QtGui.QApplication.translate("Form", "efx", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(4).setText(QtGui.QApplication.translate("Form", "fac", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(5).setText(QtGui.QApplication.translate("Form", "lay", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(6).setText(QtGui.QApplication.translate("Form", "lit", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(7).setText(QtGui.QApplication.translate("Form", "mod", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(8).setText(QtGui.QApplication.translate("Form", "pro", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(9).setText(QtGui.QApplication.translate("Form", "rig", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(10).setText(QtGui.QApplication.translate("Form", "shf", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(11).setText(QtGui.QApplication.translate("Form", "tex", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.setSortingEnabled(__sortingEnabled)
        self.addEmployee_pb.setText(QtGui.QApplication.translate("Form", "Add Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAvailability_pb.setText(QtGui.QApplication.translate("Form", "Check availability", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Add Employee", None, QtGui.QApplication.UnicodeUTF8))

