# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\user\durgesh.n\workspace\SHIVA-V2\ui\production.ui'
#
# Created: Wed Jun 28 18:17:25 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 544)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.project_cb = QtGui.QComboBox(self.tab)
        self.project_cb.setObjectName("project_cb")
        self.verticalLayout.addWidget(self.project_cb)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.episode_cb = QtGui.QComboBox(self.tab)
        self.episode_cb.setObjectName("episode_cb")
        self.verticalLayout_2.addWidget(self.episode_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.dept_cb = QtGui.QComboBox(self.tab)
        self.dept_cb.setObjectName("dept_cb")
        self.verticalLayout_3.addWidget(self.dept_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.emplyee_le = QtGui.QLineEdit(self.tab)
        self.emplyee_le.setObjectName("emplyee_le")
        self.verticalLayout_4.addWidget(self.emplyee_le)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tableWidget = QtGui.QTableWidget(self.tab)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem4 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.assign_pb = QtGui.QPushButton(self.tab)
        self.assign_pb.setObjectName("assign_pb")
        self.horizontalLayout_2.addWidget(self.assign_pb)
        self.approve_pb = QtGui.QPushButton(self.tab)
        self.approve_pb.setObjectName("approve_pb")
        self.horizontalLayout_2.addWidget(self.approve_pb)
        self.retake_pb = QtGui.QPushButton(self.tab)
        self.retake_pb.setObjectName("retake_pb")
        self.horizontalLayout_2.addWidget(self.retake_pb)
        self.reassign_pb = QtGui.QPushButton(self.tab)
        self.reassign_pb.setObjectName("reassign_pb")
        self.horizontalLayout_2.addWidget(self.reassign_pb)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.addSeq_tab = QtGui.QWidget()
        self.addSeq_tab.setObjectName("addSeq_tab")
        self.gridLayout_6 = QtGui.QGridLayout(self.addSeq_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtGui.QLabel(self.addSeq_tab)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit = QtGui.QLineEdit(self.addSeq_tab)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.addSeq_tab)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_9 = QtGui.QLabel(self.addSeq_tab)
        self.label_9.setMinimumSize(QtCore.QSize(70, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.lineEdit_2 = QtGui.QLineEdit(self.addSeq_tab)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.pushButton_2 = QtGui.QPushButton(self.addSeq_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_9.addWidget(self.pushButton_2)
        self.gridLayout_6.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.addSeq_tab, "")
        self.addEmp_tab = QtGui.QWidget()
        self.addEmp_tab.setObjectName("addEmp_tab")
        self.gridLayout_5 = QtGui.QGridLayout(self.addEmp_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtGui.QLabel(self.addEmp_tab)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.addEmployee_le = QtGui.QLineEdit(self.addEmp_tab)
        self.addEmployee_le.setObjectName("addEmployee_le")
        self.horizontalLayout_4.addWidget(self.addEmployee_le)
        self.checkAvailability_pb = QtGui.QPushButton(self.addEmp_tab)
        self.checkAvailability_pb.setObjectName("checkAvailability_pb")
        self.horizontalLayout_4.addWidget(self.checkAvailability_pb)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtGui.QLabel(self.addEmp_tab)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.activeEmployee_lw = QtGui.QListWidget(self.addEmp_tab)
        self.activeEmployee_lw.setObjectName("activeEmployee_lw")
        self.verticalLayout_5.addWidget(self.activeEmployee_lw)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtGui.QLabel(self.addEmp_tab)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.dept_lw = QtGui.QListWidget(self.addEmp_tab)
        self.dept_lw.setObjectName("dept_lw")
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        QtGui.QListWidgetItem(self.dept_lw)
        self.verticalLayout_6.addWidget(self.dept_lw)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.addEmployee_pb = QtGui.QPushButton(self.addEmp_tab)
        self.addEmployee_pb.setObjectName("addEmployee_pb")
        self.verticalLayout_8.addWidget(self.addEmployee_pb)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.tabWidget.addTab(self.addEmp_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Select Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Select Episode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Select Department", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Select Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.emplyee_le.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Enter name here..", None, QtGui.QApplication.UnicodeUTF8))
        self.assign_pb.setText(QtGui.QApplication.translate("MainWindow", "Assign", None, QtGui.QApplication.UnicodeUTF8))
        self.approve_pb.setText(QtGui.QApplication.translate("MainWindow", "Approoved", None, QtGui.QApplication.UnicodeUTF8))
        self.retake_pb.setText(QtGui.QApplication.translate("MainWindow", "Retake", None, QtGui.QApplication.UnicodeUTF8))
        self.reassign_pb.setText(QtGui.QApplication.translate("MainWindow", "Reassign", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Assign Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Exel file path :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Exel File path here.....", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "File Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Sheet Name :", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Which Sheets to add with \",\" separation..., i.e : ep105, ep110, ep112", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Add Sheet(s) To Databse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addSeq_tab), QtGui.QApplication.translate("MainWindow", "Add Sequences", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Add New Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAvailability_pb.setText(QtGui.QApplication.translate("MainWindow", "Check availability", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Active Employees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Departments", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.dept_lw.isSortingEnabled()
        self.dept_lw.setSortingEnabled(False)
        self.dept_lw.item(0).setText(QtGui.QApplication.translate("MainWindow", "ani", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(1).setText(QtGui.QApplication.translate("MainWindow", "art", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(2).setText(QtGui.QApplication.translate("MainWindow", "cbs", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(3).setText(QtGui.QApplication.translate("MainWindow", "efx", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(4).setText(QtGui.QApplication.translate("MainWindow", "fac", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(5).setText(QtGui.QApplication.translate("MainWindow", "lay", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(6).setText(QtGui.QApplication.translate("MainWindow", "lit", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(7).setText(QtGui.QApplication.translate("MainWindow", "mod", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(8).setText(QtGui.QApplication.translate("MainWindow", "pro", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(9).setText(QtGui.QApplication.translate("MainWindow", "rig", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(10).setText(QtGui.QApplication.translate("MainWindow", "shf", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.item(11).setText(QtGui.QApplication.translate("MainWindow", "tex", None, QtGui.QApplication.UnicodeUTF8))
        self.dept_lw.setSortingEnabled(__sortingEnabled)
        self.addEmployee_pb.setText(QtGui.QApplication.translate("MainWindow", "Add Employee", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addEmp_tab), QtGui.QApplication.translate("MainWindow", "Add Employee", None, QtGui.QApplication.UnicodeUTF8))

